# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a674db328eb6ad64229053a551e64634247cab9e2838045f7202e5259754f80357d65096b8020c0c24c87c10822633637416cfcaa24d3b0228578f5deb64e541

test:
  secret_key_base: 0129a8f46b5faaa475c8c51c8b5abd345495531eda93b03ffdbe620b9ce46b7f00bd211853bb21bc7ab8a13a3201c26f0fee6f32471b27562195fbc65a89a22f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
